copyright = "©2019 Everton da Rosa."
languageCode = "pt_br"

[params]
style = "dark"
dateFormat = "Monday, 2 January 2006"
slogan = "Notícias, ideias e material sobre Contabilidade Pública."
logo = "images/caduceu.png"

[params.comments]
enable = true

[params.math]
enable = true
use = "katex"

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "Blog"
url = "/blog"

[[params.nav.custom]]
title = "Categorias"
url = "/categories"

[[params.nav.custom]]
title = "Tags"
url = "/tags"

[[params.nav.custom]]
title = "Sobre"
url = "/sobre"